FROM openjdk:8-jdk-alpine
COPY . /
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
RUN echo 'JACK COME IN1;' >> /app.txt
CMD cat /app.txt